###########
# site.url, site.title

url:   'http://scilifelabcourses.github.io'
title: 'SciLifeLab Courses'
ga: 'UA-23985298-11'


########
# more settings

highlighter: pygments
permalink: pretty

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

sass:
  sass_dir: css
  style:    expanded



exclude:
- README.md


safe: true
lsi: false

