###########
# site.url, site.title

url:   'http://scilifelabcourses.github.io/'
title: 'Jekyll Bootstrap Theeme'


########
# more settings

#markdown: kramdown

sass:
  sass_dir: css
  style:    expanded



exclude:
- README.md


safe: true
lsi: false

