###########
# site.url, site.title

url:   'http://scilifelabcourses.github.io'
title: 'SciLifeLab Courses'


########
# more settings

markdown: redcarpet2

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

sass:
  sass_dir: css
  style:    expanded



exclude:
- README.md


safe: true
lsi: false

